connection_type: ap
lower_blue:
- 100
- 80
- 50
upper_blue:
- 130
- 255
- 255
roi_row_offsets:
- 320  # 最远处
- 313
- 306
- 299
- 292
- 285
- 278
- 271
- 264
- 257
- 250
- 243
- 236
- 229
- 222
- 215
- 208
- 201
- 194
- 187
- 180
- 173
- 166
- 159
- 152
- 145
- 138
- 131
- 124
- 117
- 110
- 103
- 96
- 89
- 82
- 75
- 68
- 61
- 60   # 最近处（确保包含60）
min_white_pixels: 12
main_pid_params:
- 0.2
- 0.001
- 0.05
- 80
curved_pid_params:
- 0.8
- 0.003
- 0.12
- 150
gimbal_pitch: -25.0
gimbal_yaw: 0.0
gimbal_speed: 100
max_line_lost_frames: 10
position_history_length: 12
curvature_history_length: 8
base_speed_straight: 1.2
base_speed_curve: 0.9
curvature_enter_threshold: 0.2
curvature_exit_threshold: 0.1
drift_enabled: true
drift_aggression: 1.0
drift_speed_boost: 1.1
min_drift_curvature: 0.25
